workflow_details:
  description: ''
  name: collared_lions_report
time_range:
  timezone:
    label: UTC
    tzCode: UTC
    name: UTC
    utc: '+03:00'
  time_format: '%d %b %Y %H:%M:%S'
  since: '2025-02-01T06:21:00.000Z'
  until: '2026-01-31T06:22:00.000Z'
groupers:
  groupers: []
er_client_name:
  data_source:
    name: lg
subject_obs:
  filter: clean
  subject_group_name: Collared Lions
subject_traj:
  trajectory_segment_filter:
    min_length_meters: 0.001
    max_length_meters: 5000
    min_time_secs: 1
    max_time_secs: 21600
    min_speed_kmhr: 0.01
    max_speed_kmhr: 20
td:
  auto_scale_or_custom_cell_size:
    auto_scale_or_custom: Auto-scale
  max_speed_factor: 1.05
  expansion_factor: 1.05
zoom_to_envelope:
  expansion_factor: 1.05
