# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.analysis import (
    calculate_elliptical_time_density as calculate_elliptical_time_density,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_nunique as dataframe_column_nunique,
)
from ecoscope.platform.tasks.analysis import (
    dataframe_column_sum as dataframe_column_sum,
)
from ecoscope.platform.tasks.analysis import summarize_df as summarize_df
from ecoscope.platform.tasks.config import prefix_string_var as prefix_string_var
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import groupbykey as groupbykey
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.groupby import split_groups as split_groups
from ecoscope.platform.tasks.io import (
    get_subjectgroup_observations as get_subjectgroup_observations,
)
from ecoscope.platform.tasks.io import persist_df as persist_df
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.preprocessing import (
    process_relocations as process_relocations,
)
from ecoscope.platform.tasks.preprocessing import (
    relocations_to_trajectory as relocations_to_trajectory,
)
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_single_value_widget_single_view as create_single_value_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import merge_widget_views as merge_widget_views
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import (
    any_keyed_iterables_are_skips as any_keyed_iterables_are_skips,
)
from ecoscope.platform.tasks.skip import never as never
from ecoscope.platform.tasks.transformation import (
    add_temporal_index as add_temporal_index,
)
from ecoscope.platform.tasks.transformation import (
    apply_classification as apply_classification,
)
from ecoscope.platform.tasks.transformation import apply_color_map as apply_color_map
from ecoscope.platform.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope.platform.tasks.transformation import map_columns as map_columns
from ecoscope_workflows_ext_custom.tasks.io import html_to_png as html_to_png
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_path_layer as create_path_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map_1
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_lion_guardians.tasks.reporting import (
    create_collared_lions_context as create_collared_lions_context,
)
from ecoscope_workflows_ext_lion_guardians.tasks.reporting import (
    render_docx_page as render_docx_page,
)
from ecoscope_workflows_ext_ste.tasks.io import (
    fetch_and_persist_file as fetch_and_persist_file,
)
from ecoscope_workflows_ext_ste.tasks.reporting import (
    create_context_page as create_context_page,
)
from ecoscope_workflows_ext_ste.tasks.reporting import (
    merge_docx_documents as merge_docx_documents,
)
from ecoscope_workflows_ext_ste.tasks.reporting import (
    prepare_cover_metadata as prepare_cover_metadata,
)
from ecoscope_workflows_ext_ste.tasks.results import (
    create_spatial_features_layer as create_spatial_features_layer,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    compute_view_state_from_gdf as compute_view_state_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    envelope_gdf as envelope_gdf,
)
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    get_spatial_features as get_spatial_features,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    column_first_unique_value as column_first_unique_value,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    round_off_values as round_off_values,
)
from ecoscope_workflows_ext_ste.tasks.transformation import safe_string as safe_string
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    get_timezone = (
        task(get_timezone_from_time_range)
        .validate()
        .set_task_instance_id("get_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(time_range=time_range, **(params.get("get_timezone") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupers=[{"index_name": "subject_name"}], **(params.get("groupers") or {})
        )
        .call()
    )

    er_client_name = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_client_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_client_name") or {}))
        .call()
    )

    base_map_defs = (
        task(set_base_maps_pydeck)
        .validate()
        .set_task_instance_id("base_map_defs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 1,
                    "max_zoom": 15,
                },
                {
                    "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.15,
                    "max_zoom": 15,
                },
            ],
            **(params.get("base_map_defs") or {}),
        )
        .call()
    )

    select_geo_er = (
        task(get_spatial_features)
        .validate()
        .set_task_instance_id("select_geo_er")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            layers=[
                {
                    "query": {"feature_type": "Conservancies"},
                    "style": [
                        {
                            "polygon": [
                                {
                                    "fill_color": ["#8fbc8b"],
                                    "stroke_color": "#8fbc8b",
                                    "fill_opacity": 0.75,
                                    "stroke_width": 1.75,
                                }
                            ]
                        }
                    ],
                    "group_by": "type_name",
                    "legend_title": "Boundaries",
                },
                {
                    "query": {"feature_type": "Group Ranch Boundaries"},
                    "style": [
                        {
                            "polygon": [
                                {
                                    "fill_opacity": 0,
                                    "stroke_color": "#000000",
                                    "stroke_width": 1.25,
                                }
                            ]
                        }
                    ],
                    "group_by": "type_name",
                    "legend_title": "",
                },
            ],
            **(params.get("select_geo_er") or {}),
        )
        .call()
    )

    spatial_features_layer = (
        task(create_spatial_features_layer)
        .validate()
        .set_task_instance_id("spatial_features_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            geodataframes=select_geo_er, **(params.get("spatial_features_layer") or {})
        )
        .call()
    )

    persist_cover_page = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("persist_cover_page")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/kyjd9ii9nul1osbkezl5w/collared_lions_cover_page.docx?rlkey=4nl68thyqzd0n49wnr1770u0x&st=fnpsvt9i&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("persist_cover_page") or {}),
        )
        .call()
    )

    persist_indv_subject_page = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("persist_indv_subject_page")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/v69q5ja7whtb033adq829/collared_lion_subject_template.docx?rlkey=zaf9iknc61zukii4xzwwwuu6o&st=1gj1vbk3&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("persist_indv_subject_page") or {}),
        )
        .call()
    )

    subject_obs = (
        task(get_subjectgroup_observations)
        .validate()
        .set_task_instance_id("subject_obs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            include_details=False,
            include_subjectsource_details=False,
            filter="clean",
            **(params.get("subject_obs") or {}),
        )
        .call()
    )

    convert_relocs_timezone = (
        task(convert_values_to_timezone)
        .validate()
        .set_task_instance_id("convert_relocs_timezone")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_obs,
            timezone=get_timezone,
            columns=["fixtime"],
            **(params.get("convert_relocs_timezone") or {}),
        )
        .call()
    )

    subject_reloc = (
        task(process_relocations)
        .validate()
        .set_task_instance_id("subject_reloc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            observations=convert_relocs_timezone,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__subject_subtype",
                "extra__subject__sex",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params.get("subject_reloc") or {}),
        )
        .call()
    )

    persist_relocs = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_relocs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geoparquet",
            filename="relocations",
            df=subject_reloc,
            **(params.get("persist_relocs") or {}),
        )
        .call()
    )

    subject_traj = (
        task(relocations_to_trajectory)
        .validate()
        .set_task_instance_id("subject_traj")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            relocations=subject_reloc,
            trajectory_segment_filter={
                "min_length_meters": 10,
                "max_length_meters": 10000,
                "min_time_secs": 10,
                "max_time_secs": 21600,
                "min_speed_kmhr": 1,
                "max_speed_kmhr": 30,
            },
            **(params.get("subject_traj") or {}),
        )
        .call()
    )

    persist_trajs = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_trajs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="geoparquet",
            filename="trajectories",
            df=subject_traj,
            **(params.get("persist_trajs") or {}),
        )
        .call()
    )

    traj_add_temporal_index = (
        task(add_temporal_index)
        .validate()
        .set_task_instance_id("traj_add_temporal_index")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=subject_traj,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    classify_trajectories_speed_bins = (
        task(apply_classification)
        .validate()
        .set_task_instance_id("classify_trajectories_speed_bins")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=traj_add_temporal_index,
            input_column_name="speed_kmhr",
            output_column_name="speed_bins",
            classification_options={"scheme": "equal_interval", "k": 6},
            label_options={"label_range": False, "label_decimals": 1},
            **(params.get("classify_trajectories_speed_bins") or {}),
        )
        .call()
    )

    rename_traj_cols = (
        task(map_columns)
        .validate()
        .set_task_instance_id("rename_traj_cols")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            raise_if_not_found=True,
            drop_columns=[],
            retain_columns=[],
            rename_columns={
                "extra__name": "subject_name",
                "extra__sex": "subject_sex",
                "extra__subject_subtype": "subject_subtype",
            },
            df=classify_trajectories_speed_bins,
            **(params.get("rename_traj_cols") or {}),
        )
        .call()
    )

    split_subject_traj_groups = (
        task(split_groups)
        .validate()
        .set_task_instance_id("split_subject_traj_groups")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_traj_cols,
            groupers=groupers,
            **(params.get("split_subject_traj_groups") or {}),
        )
        .call()
    )

    unique_subject_name = (
        task(column_first_unique_value)
        .validate()
        .set_task_instance_id("unique_subject_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="subject_name", **(params.get("unique_subject_name") or {})
        )
        .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
    )

    safe_subject_name = (
        task(safe_string)
        .validate()
        .set_task_instance_id("safe_subject_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("safe_subject_name") or {}))
        .mapvalues(argnames=["value"], argvalues=unique_subject_name)
    )

    tracks_filename = (
        task(prefix_string_var)
        .validate()
        .set_task_instance_id("tracks_filename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="_tracks.html", **(params.get("tracks_filename") or {}))
        .mapvalues(argnames=["prefix"], argvalues=safe_subject_name)
    )

    hr_filename = (
        task(prefix_string_var)
        .validate()
        .set_task_instance_id("hr_filename")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(var="_homerange.html", **(params.get("hr_filename") or {}))
        .mapvalues(argnames=["prefix"], argvalues=safe_subject_name)
    )

    zoom_to_envelope = (
        task(envelope_gdf)
        .validate()
        .set_task_instance_id("zoom_to_envelope")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("zoom_to_envelope") or {}))
        .mapvalues(argnames=["gdf"], argvalues=split_subject_traj_groups)
    )

    gdf_image_extent = (
        task(compute_view_state_from_gdf)
        .validate()
        .set_task_instance_id("gdf_image_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            pitch=0, bearing=0, max_zoom=15, **(params.get("gdf_image_extent") or {})
        )
        .mapvalues(argnames=["gdf"], argvalues=zoom_to_envelope)
    )

    td = (
        task(calculate_elliptical_time_density)
        .validate()
        .set_task_instance_id("td")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            crs="ESRI:53042",
            percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
            nodata_value="nan",
            band_count=1,
            **(params.get("td") or {}),
        )
        .mapvalues(argnames=["trajectory_gdf"], argvalues=split_subject_traj_groups)
    )

    td_colormap = (
        task(apply_color_map)
        .validate()
        .set_task_instance_id("td_colormap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            input_column_name="percentile",
            colormap="RdYlGn",
            output_column_name="percentile_colormap",
            **(params.get("td_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=td)
    )

    td_map_layer = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("td_map_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": "percentile_colormap",
                "get_line_color": "percentile_colormap",
                "opacity": 0.45,
                "get_line_width": 1.55,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Home Range Percentiles",
                "label_column": "percentile",
                "color_column": "percentile_colormap",
                "sort": "ascending",
                "label_suffix": None,
            },
            **(params.get("td_map_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=td_colormap)
    )

    combine_hr_map_layers = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_hr_map_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=spatial_features_layer,
            **(params.get("combine_hr_map_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=td_map_layer)
    )

    zip_hr_with_viewstate = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_hr_with_viewstate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_hr_map_layers, gdf_image_extent],
            **(params.get("zip_hr_with_viewstate") or {}),
        )
        .call()
    )

    td_ecomap = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("td_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            static=False,
            title=None,
            max_zoom=15,
            legend_style={"placement": "bottom-right", "title": "ETD Metrics"},
            **(params.get("td_ecomap") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=zip_hr_with_viewstate
        )
    )

    hr_text = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("hr_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(iterables=[hr_filename, td_ecomap], **(params.get("hr_text") or {}))
        .call()
    )

    td_ecomap_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("td_ecomap_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix=None,
            **(params.get("td_ecomap_html_url") or {}),
        )
        .mapvalues(argnames=["filename", "text"], argvalues=hr_text)
    )

    td_map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("td_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Home Range Metrics", **(params.get("td_map_widget") or {}))
        .map(argnames=["view", "data"], argvalues=td_ecomap_html_url)
    )

    td_grouped_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("td_grouped_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=td_map_widget, **(params.get("td_grouped_map_widget") or {}))
        .call()
    )

    summary_table = (
        task(summarize_df)
        .validate()
        .set_task_instance_id("summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            groupby_cols=["subject_name"],
            summary_params=[
                {
                    "display_name": "mean_speed",
                    "aggregator": "mean",
                    "column": "speed_kmhr",
                    "decimal_places": 2,
                },
                {
                    "display_name": "min_speed",
                    "aggregator": "min",
                    "column": "speed_kmhr",
                    "decimal_places": 2,
                },
                {
                    "display_name": "max_speed",
                    "aggregator": "max",
                    "column": "speed_kmhr",
                    "decimal_places": 2,
                },
                {
                    "display_name": "total_distance",
                    "aggregator": "sum",
                    "column": "dist_meters",
                    "original_unit": "m",
                    "new_unit": "km",
                    "decimal_places": 2,
                },
            ],
            reset_index=True,
            **(params.get("summary_table") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
    )

    persist_summary_table = (
        task(persist_df)
        .validate()
        .set_task_instance_id("persist_summary_table")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filetype="csv",
            filename=None,
            **(params.get("persist_summary_table") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=summary_table)
    )

    collared_html_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("collared_html_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("collared_html_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=td_ecomap_html_url)
    )

    generate_track_layers = (
        task(create_path_layer_1)
        .validate()
        .set_task_instance_id("generate_track_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "get_color": [30, 144, 255],
                "get_width": 1.25,
                "width_scale": 1,
                "width_min_pixels": 2,
                "width_max_pixels": 8,
                "width_units": "pixels",
                "cap_rounded": True,
                "joint_rounded": True,
                "billboard": False,
                "opacity": 0.45,
                "stroked": True,
            },
            legend={
                "title": "Subject Tracks",
                "values": [{"label": "Tracks", "color": "#1e90ff"}],
            },
            **(params.get("generate_track_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=split_subject_traj_groups)
    )

    combine_track_layers = (
        task(combine_deckgl_map_layers)
        .validate()
        .set_task_instance_id("combine_track_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            static_layers=spatial_features_layer,
            **(params.get("combine_track_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=generate_track_layers)
    )

    zip_tracks_viewstate = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("zip_tracks_viewstate")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[combine_track_layers, gdf_image_extent],
            **(params.get("zip_tracks_viewstate") or {}),
        )
        .call()
    )

    draw_track_map = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_track_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=base_map_defs,
            static=False,
            title=None,
            max_zoom=15,
            legend_style={"placement": "bottom-right"},
            **(params.get("draw_track_map") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=zip_tracks_viewstate
        )
    )

    movement_text = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("movement_text")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[tracks_filename, draw_track_map],
            **(params.get("movement_text") or {}),
        )
        .call()
    )

    track_html_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("track_html_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="tracks",
            **(params.get("track_html_url") or {}),
        )
        .mapvalues(argnames=["filename", "text"], argvalues=movement_text)
    )

    track_html_png = (
        task(html_to_png)
        .validate()
        .set_task_instance_id("track_html_png")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={
                "full_page": False,
                "device_scale_factor": 2.0,
                "wait_for_timeout": 40000,
                "max_concurrent_pages": 1,
            },
            **(params.get("track_html_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=track_html_url)
    )

    trackmap_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("trackmap_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Subject Tracks", **(params.get("trackmap_widget") or {}))
        .map(argnames=["view", "data"], argvalues=track_html_url)
    )

    sm_grouped_map_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("sm_grouped_map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(widgets=trackmap_widget, **(params.get("sm_grouped_map_widget") or {}))
        .call()
    )

    calc_mean_speed = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("calc_mean_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="mean_speed", **(params.get("calc_mean_speed") or {}))
        .mapvalues(argnames=["df"], argvalues=summary_table)
    )

    round_mean_speed = (
        task(round_off_values)
        .validate()
        .set_task_instance_id("round_mean_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dp=2, **(params.get("round_mean_speed") or {}))
        .mapvalues(argnames=["value"], argvalues=calc_mean_speed)
    )

    calc_min_speed = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("calc_min_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="min_speed", **(params.get("calc_min_speed") or {}))
        .mapvalues(argnames=["df"], argvalues=summary_table)
    )

    round_min_speed = (
        task(round_off_values)
        .validate()
        .set_task_instance_id("round_min_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dp=2, **(params.get("round_min_speed") or {}))
        .mapvalues(argnames=["value"], argvalues=calc_min_speed)
    )

    calc_max_speed = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("calc_max_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(column_name="max_speed", **(params.get("calc_max_speed") or {}))
        .mapvalues(argnames=["df"], argvalues=summary_table)
    )

    round_max_speed = (
        task(round_off_values)
        .validate()
        .set_task_instance_id("round_max_speed")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dp=2, **(params.get("round_max_speed") or {}))
        .mapvalues(argnames=["value"], argvalues=calc_max_speed)
    )

    total_distance_covered = (
        task(dataframe_column_sum)
        .validate()
        .set_task_instance_id("total_distance_covered")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            column_name="total_distance", **(params.get("total_distance_covered") or {})
        )
        .mapvalues(argnames=["df"], argvalues=summary_table)
    )

    round_total_distance = (
        task(round_off_values)
        .validate()
        .set_task_instance_id("round_total_distance")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dp=2, **(params.get("round_total_distance") or {}))
        .mapvalues(argnames=["value"], argvalues=total_distance_covered)
    )

    unique_subjects = (
        task(dataframe_column_nunique)
        .validate()
        .set_task_instance_id("unique_subjects")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=rename_traj_cols,
            column_name="subject_name",
            **(params.get("unique_subjects") or {}),
        )
        .call()
    )

    persist_logo = (
        task(fetch_and_persist_file)
        .validate()
        .set_task_instance_id("persist_logo")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            url="https://www.dropbox.com/scl/fi/8oohb6i0kcj0q3qsud9l4/lion-guardians.png?rlkey=4kdqytux2qyftb5sgnaigyuyz&st=os6i6j6h&dl=0",
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            overwrite_existing=False,
            retries=3,
            unzip=False,
            **(params.get("persist_logo") or {}),
        )
        .call()
    )

    create_cover_tpl_context = (
        task(prepare_cover_metadata)
        .validate()
        .set_task_instance_id("create_cover_tpl_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            org_logo_path=persist_logo,
            report_period=time_range,
            prepared_by="Ecoscope",
            extra_fields={"count": unique_subjects},
            time_generated_format="%Y-%m-%d %H:%M:%S",
            **(params.get("create_cover_tpl_context") or {}),
        )
        .call()
    )

    persist_collar_cover_page = (
        task(create_context_page)
        .validate()
        .set_task_instance_id("persist_collar_cover_page")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            template_path=persist_cover_page,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            context=create_cover_tpl_context,
            filename="cover_page.docx",
            **(params.get("persist_collar_cover_page") or {}),
        )
        .call()
    )

    group_context_values = (
        task(groupbykey)
        .validate()
        .set_task_instance_id("group_context_values")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_keyed_iterables_are_skips,
            ],
            unpack_depth=1,
        )
        .partial(
            iterables=[
                split_subject_traj_groups,
                round_total_distance,
                collared_html_png,
                track_html_png,
            ],
            **(params.get("group_context_values") or {}),
        )
        .call()
    )

    build_collared_context = (
        task(create_collared_lions_context)
        .validate()
        .set_task_instance_id("build_collared_context")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("build_collared_context") or {}))
        .mapvalues(
            argnames=["df", "total_distance", "home_range", "speed_map"],
            argvalues=group_context_values,
        )
    )

    create_grouper_doc = (
        task(render_docx_page)
        .validate()
        .set_task_instance_id("create_grouper_doc")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            template_path=persist_indv_subject_page,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename=None,
            strict_images=True,
            box_h_cm=6.5,
            box_w_cm=11.11,
            **(params.get("create_grouper_doc") or {}),
        )
        .mapvalues(argnames=["context"], argvalues=build_collared_context)
    )

    merge_collared_docs = (
        task(merge_docx_documents)
        .validate()
        .set_task_instance_id("merge_collared_docs")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            cover_page_path=persist_collar_cover_page,
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            context_page_items=create_grouper_doc,
            filename="overall_report.docx",
            order_by="name",
            **(params.get("merge_collared_docs") or {}),
        )
        .call()
    )

    total_mean_speed_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_mean_speed_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Mean Speed",
            decimal_places=2,
            **(params.get("total_mean_speed_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=round_mean_speed)
    )

    total_mean_speed_sv_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_mean_speed_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_mean_speed_widgets,
            **(params.get("total_mean_speed_sv_widget") or {}),
        )
        .call()
    )

    total_min_speed_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_min_speed_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Min Speed",
            decimal_places=2,
            **(params.get("total_min_speed_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=round_min_speed)
    )

    total_min_speed_sv_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_min_speed_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_min_speed_widgets,
            **(params.get("total_min_speed_sv_widget") or {}),
        )
        .call()
    )

    total_max_speed_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_max_speed_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Max Speed",
            decimal_places=2,
            **(params.get("total_max_speed_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=round_max_speed)
    )

    total_max_speed_sv_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_max_speed_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_max_speed_widgets,
            **(params.get("total_max_speed_sv_widget") or {}),
        )
        .call()
    )

    total_distance_widgets = (
        task(create_single_value_widget_single_view)
        .validate()
        .set_task_instance_id("total_distance_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Distance covered",
            decimal_places=2,
            **(params.get("total_distance_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=round_total_distance)
    )

    total_distance_sv_widget = (
        task(merge_widget_views)
        .validate()
        .set_task_instance_id("total_distance_sv_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            widgets=total_distance_widgets,
            **(params.get("total_distance_sv_widget") or {}),
        )
        .call()
    )

    lg_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("lg_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                total_mean_speed_sv_widget,
                total_min_speed_sv_widget,
                total_max_speed_sv_widget,
                total_distance_sv_widget,
                td_grouped_map_widget,
                sm_grouped_map_widget,
            ],
            time_range=time_range,
            groupers=groupers,
            **(params.get("lg_dashboard") or {}),
        )
        .call()
    )

    return lg_dashboard
