# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Collared Lions Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.analysis import (
    dataframe_column_nunique,
    dataframe_column_sum,
)
from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers, split_groups
from ecoscope_workflows_core.tasks.io import persist_text, set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view,
    create_single_value_widget_single_view,
    gather_dashboard,
    merge_widget_views,
)
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped,
    any_is_empty_df,
    never,
)
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_ext_custom.tasks import html_to_png
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_elliptical_time_density,
    summarize_df,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import (
    get_subjectgroup_observations,
    persist_df,
)
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    process_relocations,
    relocations_to_trajectory,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_ext_lion_guardians.tasks import (
    add_totals_row,
    clean_file_keys,
    combine_docx_files,
    create_cover_context_page,
    create_geojson_layer,
    create_map_layers,
    create_report_context,
    download_file_and_persist,
    draw_custom_map,
    load_geospatial_files,
    make_text_layer,
    merge_static_and_grouped_layers,
    round_off_values,
    select_koi,
    set_custom_base_maps,
    view_state_deck_gdf,
    zip_grouped_by_key,
)

# %% [markdown]
# ## Set Workflow Details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time Range

# %%
# parameters

time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **time_range_params)
    .call()
)


# %% [markdown]
# ## Set Groupers

# %%
# parameters

groupers_params = dict(
    groupers=...,
)

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .partial(**groupers_params)
    .call()
)


# %% [markdown]
# ## Data Source

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.set_task_instance_id("er_client_name")
    .handle_errors()
    .with_tracing()
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Base Maps

# %%
# parameters

base_map_defs_params = dict(
    base_maps=...,
)

# %%
# call the task


base_map_defs = (
    set_custom_base_maps.set_task_instance_id("base_map_defs")
    .handle_errors()
    .with_tracing()
    .partial(**base_map_defs_params)
    .call()
)


# %% [markdown]
# ## Download amboseli group ranches

# %%
# parameters

persist_ambo_gpkg_params = dict()

# %%
# call the task


persist_ambo_gpkg = (
    download_file_and_persist.set_task_instance_id("persist_ambo_gpkg")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://www.dropbox.com/scl/fi/phlc488gxqpcvr6ua3vk7/amboseli_group_ranch_boundaries.gpkg?rlkey=p5ztypwmj4ndjova9xe2ssiun&st=pknuicus&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **persist_ambo_gpkg_params,
    )
    .call()
)


# %% [markdown]
# ## Download collared lions cover page

# %%
# parameters

persist_cover_page_params = dict()

# %%
# call the task


persist_cover_page = (
    download_file_and_persist.set_task_instance_id("persist_cover_page")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://www.dropbox.com/scl/fi/1cbilbjq8625gsd5bb45m/collared_lions_cover_page.docx?rlkey=j6aq1bjrrsiv0qj4bghwywe1d&st=eqttsiau&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **persist_cover_page_params,
    )
    .call()
)


# %% [markdown]
# ## Download collared subject page

# %%
# parameters

persist_indv_subject_page_params = dict()

# %%
# call the task


persist_indv_subject_page = (
    download_file_and_persist.set_task_instance_id("persist_indv_subject_page")
    .handle_errors()
    .with_tracing()
    .partial(
        url="https://www.dropbox.com/scl/fi/rdjej0c0dva7y8czw82de/collared_lion_subject_template.docx?rlkey=479h5pmpvjncgn314hd2r80yh&st=iuuc1o6t&dl=0",
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        overwrite_existing=False,
        retries=3,
        unzip=False,
        **persist_indv_subject_page_params,
    )
    .call()
)


# %% [markdown]
# ## Load downloaded shapefiles

# %%
# parameters

load_local_shapefiles_params = dict()

# %%
# call the task


load_local_shapefiles = (
    load_geospatial_files.set_task_instance_id("load_local_shapefiles")
    .handle_errors()
    .with_tracing()
    .partial(
        config={"path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"]},
        **load_local_shapefiles_params,
    )
    .call()
)


# %% [markdown]
# ## Clean file keys from initially loaded geospatial files

# %%
# parameters

clean_local_geo_files_params = dict()

# %%
# call the task


clean_local_geo_files = (
    clean_file_keys.set_task_instance_id("clean_local_geo_files")
    .handle_errors()
    .with_tracing()
    .partial(file_dict=load_local_shapefiles, **clean_local_geo_files_params)
    .call()
)


# %% [markdown]
# ## Create Map Layers

# %%
# parameters

create_custom_map_layers_params = dict()

# %%
# call the task


create_custom_map_layers = (
    create_map_layers.set_task_instance_id("create_custom_map_layers")
    .handle_errors()
    .with_tracing()
    .partial(
        file_dict=load_local_shapefiles,
        style_config={
            "styles": {
                "amboseli_group_ranch_boundaries": {
                    "stroked": True,
                    "filled": False,
                    "get_elevation": 50,
                    "opacity": 0.55,
                    "get_line_color": [105, 105, 105, 200],
                    "get_line_width": 3.5,
                }
            },
            "legend": {"label": ["Group ranch boundaries"], "color": ["#696969"]},
        },
        **create_custom_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Select Key of Interest to annotate text layers on the map

# %%
# parameters

filter_aoi_params = dict()

# %%
# call the task


filter_aoi = (
    select_koi.set_task_instance_id("filter_aoi")
    .handle_errors()
    .with_tracing()
    .partial(
        file_dict=clean_local_geo_files,
        key_value="amboseli_group_ranch_boundaries",
        **filter_aoi_params,
    )
    .call()
)


# %% [markdown]
# ## Create text layer

# %%
# parameters

custom_text_layer_params = dict()

# %%
# call the task


custom_text_layer = (
    make_text_layer.set_task_instance_id("custom_text_layer")
    .handle_errors()
    .with_tracing()
    .partial(
        txt_gdf=filter_aoi,
        label_column="R_NAME",
        fallback_columns=None,
        use_centroid=True,
        color=[0, 0, 0, 255],
        size=75,
        font_family="Calibri",
        font_weight="bold",
        background=False,
        background_color=None,
        background_padding=None,
        text_anchor="start",
        alignment_baseline="bottom",
        billboard=True,
        pickable=True,
        tooltip_columns=["label"],
        target_crs="epsg:4326",
        **custom_text_layer_params,
    )
    .call()
)


# %% [markdown]
# ## Get Subject Group Observations from EarthRanger

# %%
# parameters

subject_obs_params = dict(
    subject_group_name=...,
)

# %%
# call the task


subject_obs = (
    get_subjectgroup_observations.set_task_instance_id("subject_obs")
    .handle_errors()
    .with_tracing()
    .partial(
        client=er_client_name,
        time_range=time_range,
        raise_on_empty=False,
        include_details=False,
        include_subjectsource_details=False,
        **subject_obs_params,
    )
    .call()
)


# %% [markdown]
# ## Transform Observations to Relocations

# %%
# parameters

subject_reloc_params = dict()

# %%
# call the task


subject_reloc = (
    process_relocations.set_task_instance_id("subject_reloc")
    .handle_errors()
    .with_tracing()
    .partial(
        observations=subject_obs,
        relocs_columns=[
            "groupby_col",
            "fixtime",
            "junk_status",
            "geometry",
            "extra__subject__name",
            "extra__subject__subject_subtype",
            "extra__subject__sex",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **subject_reloc_params,
    )
    .call()
)


# %% [markdown]
# ## Transform Relocations to Trajectories

# %%
# parameters

subject_traj_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


subject_traj = (
    relocations_to_trajectory.set_task_instance_id("subject_traj")
    .handle_errors()
    .with_tracing()
    .partial(relocations=subject_reloc, **subject_traj_params)
    .call()
)


# %% [markdown]
# ## Add temporal index to Subject Trajectories

# %%
# parameters

traj_add_temporal_index_params = dict()

# %%
# call the task


traj_add_temporal_index = (
    add_temporal_index.set_task_instance_id("traj_add_temporal_index")
    .handle_errors()
    .with_tracing()
    .partial(
        df=subject_traj,
        time_col="segment_start",
        groupers=groupers,
        cast_to_datetime=True,
        format="mixed",
        **traj_add_temporal_index_params,
    )
    .call()
)


# %% [markdown]
# ## Split Subject Trajectories by Group

# %%
# parameters

split_subject_traj_groups_params = dict()

# %%
# call the task


split_subject_traj_groups = (
    split_groups.set_task_instance_id("split_subject_traj_groups")
    .handle_errors()
    .with_tracing()
    .partial(
        df=traj_add_temporal_index,
        groupers=groupers,
        **split_subject_traj_groups_params,
    )
    .call()
)


# %% [markdown]
# ##

# %%
# parameters

td_params = dict(
    auto_scale_or_custom_cell_size=...,
    max_speed_factor=...,
    expansion_factor=...,
)

# %%
# call the task


td = (
    calculate_elliptical_time_density.set_task_instance_id("td")
    .handle_errors()
    .with_tracing()
    .partial(
        crs="ESRI:53042",
        percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
        nodata_value="nan",
        band_count=1,
        **td_params,
    )
    .mapvalues(argnames=["trajectory_gdf"], argvalues=split_subject_traj_groups)
)


# %% [markdown]
# ## Time Density Colormap

# %%
# parameters

td_colormap_params = dict()

# %%
# call the task


td_colormap = (
    apply_color_map.set_task_instance_id("td_colormap")
    .handle_errors()
    .with_tracing()
    .partial(
        input_column_name="percentile",
        colormap="RdYlGn",
        output_column_name="percentile_colormap",
        **td_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=td)
)


# %% [markdown]
# ## Create map layer from Time Density

# %%
# parameters

td_map_layer_params = dict()

# %%
# call the task


td_map_layer = (
    create_geojson_layer.set_task_instance_id("td_map_layer")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "get_fill_color": "percentile_colormap",
            "opacity": 0.45,
            "get_line_width": 0.75,
            "stroked": True,
        },
        legend={"label_column": "percentile", "color_column": "percentile_colormap"},
        tooltip_columns=["percentile"],
        **td_map_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=td_colormap)
)


# %% [markdown]
# ## Combine Map Layers

# %%
# parameters

combine_custom_map_layers_params = dict()

# %%
# call the task


combine_custom_map_layers = (
    merge_static_and_grouped_layers.set_task_instance_id("combine_custom_map_layers")
    .handle_errors()
    .with_tracing()
    .partial(
        static_layers=[create_custom_map_layers, custom_text_layer],
        **combine_custom_map_layers_params,
    )
    .mapvalues(argnames=["grouped_layers"], argvalues=td_map_layer)
)


# %% [markdown]
# ## zoom by view state

# %%
# parameters

zoom_view_state_params = dict()

# %%
# call the task


zoom_view_state = (
    view_state_deck_gdf.set_task_instance_id("zoom_view_state")
    .handle_errors()
    .with_tracing()
    .partial(pitch=0, bearing=0, **zoom_view_state_params)
    .mapvalues(argnames=["gdf"], argvalues=td_colormap)
)


# %% [markdown]
# ## Zip layers and viewstate

# %%
# parameters

zip_layers_view_params = dict()

# %%
# call the task


zip_layers_view = (
    zip_grouped_by_key.set_task_instance_id("zip_layers_view")
    .handle_errors()
    .with_tracing()
    .partial(
        left=combine_custom_map_layers, right=zoom_view_state, **zip_layers_view_params
    )
    .call()
)


# %% [markdown]
# ## Draw Ecomap from Time Density

# %%
# parameters

td_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


td_ecomap = (
    draw_custom_map.set_task_instance_id("td_ecomap")
    .handle_errors()
    .with_tracing()
    .partial(
        tile_layers=base_map_defs,
        static=False,
        title=None,
        max_zoom=15,
        legend_style={"placement": "bottom-right", "title": "ETD Metrics"},
        **td_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=zip_layers_view)
)


# %% [markdown]
# ## Persist Ecomap as Text

# %%
# parameters

td_ecomap_html_url_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


td_ecomap_html_url = (
    persist_text.set_task_instance_id("td_ecomap_html_url")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"], **td_ecomap_html_url_params
    )
    .mapvalues(argnames=["text"], argvalues=td_ecomap)
)


# %% [markdown]
# ## Create Time Density Map Widget

# %%
# parameters

td_map_widget_params = dict()

# %%
# call the task


td_map_widget = (
    create_map_widget_single_view.set_task_instance_id("td_map_widget")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Home Range Metrics", **td_map_widget_params)
    .map(argnames=["view", "data"], argvalues=td_ecomap_html_url)
)


# %% [markdown]
# ## Merge Time Density Map Widget Views

# %%
# parameters

td_grouped_map_widget_params = dict()

# %%
# call the task


td_grouped_map_widget = (
    merge_widget_views.set_task_instance_id("td_grouped_map_widget")
    .handle_errors()
    .with_tracing()
    .partial(widgets=td_map_widget, **td_grouped_map_widget_params)
    .call()
)


# %% [markdown]
# ## Generate summary table metrics for subjects

# %%
# parameters

summary_table_params = dict()

# %%
# call the task


summary_table = (
    summarize_df.set_task_instance_id("summary_table")
    .handle_errors()
    .with_tracing()
    .partial(
        groupby_cols=["extra__name"],
        summary_params=[
            {
                "display_name": "mean_speed",
                "aggregator": "mean",
                "column": "speed_kmhr",
            },
            {"display_name": "min_speed", "aggregator": "min", "column": "speed_kmhr"},
            {"display_name": "max_speed", "aggregator": "max", "column": "speed_kmhr"},
            {
                "display_name": "total_distance",
                "aggregator": "sum",
                "columnn": "dist_meters",
                "original_unit": "m",
                "new_unit": "km",
            },
        ],
        reset_index=True,
        **summary_table_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_subject_traj_groups)
)


# %% [markdown]
# ## Add total row on summary table

# %%
# parameters

add_total_events_row_params = dict()

# %%
# call the task


add_total_events_row = (
    add_totals_row.set_task_instance_id("add_total_events_row")
    .handle_errors()
    .with_tracing()
    .partial(label_col=["extra__name"], label="Total", **add_total_events_row_params)
    .mapvalues(argnames=["df"], argvalues=summary_table)
)


# %% [markdown]
# ## Persist summary table

# %%
# parameters

persist_summary_table_params = dict(
    filename=...,
)

# %%
# call the task


persist_summary_table = (
    persist_df.set_task_instance_id("persist_summary_table")
    .handle_errors()
    .with_tracing()
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filetype="csv",
        **persist_summary_table_params,
    )
    .mapvalues(argnames=["df"], argvalues=add_total_events_row)
)


# %% [markdown]
# ## Convert collared subject html to png

# %%
# parameters

collared_html_png_params = dict()

# %%
# call the task


collared_html_png = (
    html_to_png.set_task_instance_id("collared_html_png")
    .handle_errors()
    .with_tracing()
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 25000},
        **collared_html_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=td_ecomap_html_url)
)


# %% [markdown]
# ## Unique subjects on relocs

# %%
# parameters

unique_subjects_params = dict()

# %%
# call the task


unique_subjects = (
    dataframe_column_nunique.set_task_instance_id("unique_subjects")
    .handle_errors()
    .with_tracing()
    .partial(
        df=subject_reloc, column_name="extra__subject__name", **unique_subjects_params
    )
    .call()
)


# %% [markdown]
# ## Create and persist cover page context

# %%
# parameters

create_cover_context_params = dict()

# %%
# call the task


create_cover_context = (
    create_cover_context_page.set_task_instance_id("create_cover_context")
    .handle_errors()
    .with_tracing()
    .partial(
        report_period=time_range,
        prepared_by="Ecoscope",
        count=unique_subjects,
        template_path=persist_cover_page,
        output_directory=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename="cover_page.docx",
        **create_cover_context_params,
    )
    .call()
)


# %% [markdown]
# ## Zip subject metrics and home range ecomap

# %%
# parameters

zip_metrics_etd_params = dict()

# %%
# call the task


zip_metrics_etd = (
    zip_grouped_by_key.set_task_instance_id("zip_metrics_etd")
    .handle_errors()
    .with_tracing()
    .partial(left=summary_table, right=collared_html_png, **zip_metrics_etd_params)
    .call()
)


# %% [markdown]
# ## Create individual subject context and persist

# %%
# parameters

subject_context_doc_params = dict()

# %%
# call the task


subject_context_doc = (
    create_report_context.set_task_instance_id("subject_context_doc")
    .handle_errors()
    .with_tracing()
    .partial(
        template_path=persist_indv_subject_page,
        output_directory=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        filename=None,
        validate_images=True,
        box_h_cm=9.0,
        box_w_cm=15.0,
        **subject_context_doc_params,
    )
    .mapvalues(
        argnames=["subject_metrics", "home_range_ecomap"], argvalues=zip_metrics_etd
    )
)


# %% [markdown]
# ## Generate final report

# %%
# parameters

generate_mapbook_report_params = dict()

# %%
# call the task


generate_mapbook_report = (
    combine_docx_files.set_task_instance_id("generate_mapbook_report")
    .handle_errors()
    .with_tracing()
    .partial(
        cover_page_path=create_cover_context,
        output_directory=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        context_page_items=subject_context_doc,
        filename="overall_report.docx",
        **generate_mapbook_report_params,
    )
    .call()
)


# %% [markdown]
# ## Calculate mean speed

# %%
# parameters

calc_mean_speed_params = dict()

# %%
# call the task


calc_mean_speed = (
    dataframe_column_sum.set_task_instance_id("calc_mean_speed")
    .handle_errors()
    .with_tracing()
    .partial(column_name="mean_speed", **calc_mean_speed_params)
    .mapvalues(argnames=["df"], argvalues=summary_table)
)


# %% [markdown]
# ## Round off mean speed to 2 decimal_places

# %%
# parameters

round_mean_speed_params = dict()

# %%
# call the task


round_mean_speed = (
    round_off_values.set_task_instance_id("round_mean_speed")
    .handle_errors()
    .with_tracing()
    .partial(dp=2, **round_mean_speed_params)
    .mapvalues(argnames=["value"], argvalues=calc_mean_speed)
)


# %% [markdown]
# ## Calculate min speed

# %%
# parameters

calc_min_speed_params = dict()

# %%
# call the task


calc_min_speed = (
    dataframe_column_sum.set_task_instance_id("calc_min_speed")
    .handle_errors()
    .with_tracing()
    .partial(column_name="min_speed", **calc_min_speed_params)
    .mapvalues(argnames=["df"], argvalues=summary_table)
)


# %% [markdown]
# ## Round off min speed to 2 decimal_places

# %%
# parameters

round_min_speed_params = dict()

# %%
# call the task


round_min_speed = (
    round_off_values.set_task_instance_id("round_min_speed")
    .handle_errors()
    .with_tracing()
    .partial(dp=2, **round_min_speed_params)
    .mapvalues(argnames=["value"], argvalues=calc_min_speed)
)


# %% [markdown]
# ## Calculate max speed

# %%
# parameters

calc_max_speed_params = dict()

# %%
# call the task


calc_max_speed = (
    dataframe_column_sum.set_task_instance_id("calc_max_speed")
    .handle_errors()
    .with_tracing()
    .partial(column_name="max_speed", **calc_max_speed_params)
    .mapvalues(argnames=["df"], argvalues=summary_table)
)


# %% [markdown]
# ## Round off max speed to 2 decimal_places

# %%
# parameters

round_max_speed_params = dict()

# %%
# call the task


round_max_speed = (
    round_off_values.set_task_instance_id("round_max_speed")
    .handle_errors()
    .with_tracing()
    .partial(dp=2, **round_max_speed_params)
    .mapvalues(argnames=["value"], argvalues=calc_max_speed)
)


# %% [markdown]
# ## Calculate total distance

# %%
# parameters

total_distance_covered_params = dict()

# %%
# call the task


total_distance_covered = (
    dataframe_column_sum.set_task_instance_id("total_distance_covered")
    .handle_errors()
    .with_tracing()
    .partial(column_name="total_distance", **total_distance_covered_params)
    .mapvalues(argnames=["df"], argvalues=summary_table)
)


# %% [markdown]
# ## Round off total distance to 2 decimal_places

# %%
# parameters

round_total_distance_params = dict()

# %%
# call the task


round_total_distance = (
    round_off_values.set_task_instance_id("round_total_distance")
    .handle_errors()
    .with_tracing()
    .partial(dp=2, **round_total_distance_params)
    .mapvalues(argnames=["value"], argvalues=total_distance_covered)
)


# %% [markdown]
# ## Create Single Value Widgets for total mean speed Per Group

# %%
# parameters

total_mean_speed_widgets_params = dict()

# %%
# call the task


total_mean_speed_widgets = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_mean_speed_widgets"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Mean Speed", decimal_places=1, **total_mean_speed_widgets_params)
    .map(argnames=["view", "data"], argvalues=round_mean_speed)
)


# %% [markdown]
# ## Merge per group mean speed SV widgets

# %%
# parameters

total_mean_speed_sv_widget_params = dict()

# %%
# call the task


total_mean_speed_sv_widget = (
    merge_widget_views.set_task_instance_id("total_mean_speed_sv_widget")
    .handle_errors()
    .with_tracing()
    .partial(widgets=total_mean_speed_widgets, **total_mean_speed_sv_widget_params)
    .call()
)


# %% [markdown]
# ## Create Single Value Widgets for total min speed Per Group

# %%
# parameters

total_min_speed_widgets_params = dict()

# %%
# call the task


total_min_speed_widgets = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_min_speed_widgets"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Min Speed", decimal_places=1, **total_min_speed_widgets_params)
    .map(argnames=["view", "data"], argvalues=round_min_speed)
)


# %% [markdown]
# ## Merge per group min speed SV widgets

# %%
# parameters

total_min_speed_sv_widget_params = dict()

# %%
# call the task


total_min_speed_sv_widget = (
    merge_widget_views.set_task_instance_id("total_min_speed_sv_widget")
    .handle_errors()
    .with_tracing()
    .partial(widgets=total_min_speed_widgets, **total_min_speed_sv_widget_params)
    .call()
)


# %% [markdown]
# ## Create Single Value Widgets for total max speed Per Group

# %%
# parameters

total_max_speed_widgets_params = dict()

# %%
# call the task


total_max_speed_widgets = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_max_speed_widgets"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Max Speed", decimal_places=1, **total_max_speed_widgets_params)
    .map(argnames=["view", "data"], argvalues=round_max_speed)
)


# %% [markdown]
# ## Merge per group max speed SV widgets

# %%
# parameters

total_max_speed_sv_widget_params = dict()

# %%
# call the task


total_max_speed_sv_widget = (
    merge_widget_views.set_task_instance_id("total_max_speed_sv_widget")
    .handle_errors()
    .with_tracing()
    .partial(widgets=total_max_speed_widgets, **total_max_speed_sv_widget_params)
    .call()
)


# %% [markdown]
# ## Create Single Value Widgets for total distance Per Group

# %%
# parameters

total_distance_widgets_params = dict()

# %%
# call the task


total_distance_widgets = (
    create_single_value_widget_single_view.set_task_instance_id(
        "total_distance_widgets"
    )
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Distance covered", decimal_places=1, **total_distance_widgets_params
    )
    .map(argnames=["view", "data"], argvalues=round_total_distance)
)


# %% [markdown]
# ## Merge per group total distance SV widgets

# %%
# parameters

total_distance_sv_widget_params = dict()

# %%
# call the task


total_distance_sv_widget = (
    merge_widget_views.set_task_instance_id("total_distance_sv_widget")
    .handle_errors()
    .with_tracing()
    .partial(widgets=total_distance_widgets, **total_distance_sv_widget_params)
    .call()
)


# %% [markdown]
# ## LG Dashboard

# %%
# parameters

lg_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


lg_dashboard = (
    gather_dashboard.set_task_instance_id("lg_dashboard")
    .handle_errors()
    .with_tracing()
    .partial(
        details=workflow_details,
        widgets=[
            total_mean_speed_sv_widget,
            total_min_speed_sv_widget,
            total_max_speed_sv_widget,
            total_distance_sv_widget,
            td_grouped_map_widget,
        ],
        time_range=time_range,
        groupers=groupers,
        **lg_dashboard_params,
    )
    .call()
)
