# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps
from ecoscope_workflows_ext_ecoscope.tasks.io import get_subjectgroup_observations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import process_relocations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory,
)
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_core.tasks.groupby import split_groups
from ecoscope_workflows_ext_lion_guardians.tasks import load_map_files
from ecoscope_workflows_ext_lion_guardians.tasks import create_map_layers
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_elliptical_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polygon_layer
from ecoscope_workflows_core.tasks.skip import any_is_empty_df
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped
from ecoscope_workflows_ext_lion_guardians.tasks import combine_map_layers
from ecoscope_workflows_ext_lion_guardians.tasks import create_view_state_from_gdf
from ecoscope_workflows_ext_lion_guardians.tasks import zip_grouped_by_key
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import create_map_widget_single_view
from ecoscope_workflows_core.tasks.skip import never
from ecoscope_workflows_core.tasks.results import merge_widget_views
from ecoscope_workflows_core.tasks.results import gather_dashboard
from ecoscope_workflows_ext_custom.tasks import html_to_png
from ecoscope_workflows_ext_custom.tasks import create_doc_figure
from ecoscope_workflows_ext_lion_guardians.tasks import prepare_widget_list
from ecoscope_workflows_ext_custom.tasks import gather_doc

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    workflow_details = (
        set_workflow_details.validate()
        .handle_errors(task_instance_id="workflow_details")
        .partial(**(params_dict.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        set_time_range.validate()
        .handle_errors(task_instance_id="time_range")
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z", **(params_dict.get("time_range") or {})
        )
        .call()
    )

    groupers = (
        set_groupers.validate()
        .handle_errors(task_instance_id="groupers")
        .partial(**(params_dict.get("groupers") or {}))
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .handle_errors(task_instance_id="er_client_name")
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    base_map_defs = (
        set_base_maps.validate()
        .handle_errors(task_instance_id="base_map_defs")
        .partial(**(params_dict.get("base_map_defs") or {}))
        .call()
    )

    subject_obs = (
        get_subjectgroup_observations.validate()
        .handle_errors(task_instance_id="subject_obs")
        .partial(
            client=er_client_name,
            time_range=time_range,
            raise_on_empty=False,
            include_details=False,
            include_subjectsource_details=False,
            **(params_dict.get("subject_obs") or {}),
        )
        .call()
    )

    subject_reloc = (
        process_relocations.validate()
        .handle_errors(task_instance_id="subject_reloc")
        .partial(
            observations=subject_obs,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__subject_subtype",
                "extra__subject__sex",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params_dict.get("subject_reloc") or {}),
        )
        .call()
    )

    subject_traj = (
        relocations_to_trajectory.validate()
        .handle_errors(task_instance_id="subject_traj")
        .partial(relocations=subject_reloc, **(params_dict.get("subject_traj") or {}))
        .call()
    )

    traj_add_temporal_index = (
        add_temporal_index.validate()
        .handle_errors(task_instance_id="traj_add_temporal_index")
        .partial(
            df=subject_traj,
            time_col="segment_start",
            groupers=groupers,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("traj_add_temporal_index") or {}),
        )
        .call()
    )

    split_subject_traj_groups = (
        split_groups.validate()
        .handle_errors(task_instance_id="split_subject_traj_groups")
        .partial(
            df=traj_add_temporal_index,
            groupers=groupers,
            **(params_dict.get("split_subject_traj_groups") or {}),
        )
        .call()
    )

    load_local_shapefiles = (
        load_map_files.validate()
        .handle_errors(task_instance_id="load_local_shapefiles")
        .partial(**(params_dict.get("load_local_shapefiles") or {}))
        .call()
    )

    create_custom_map_layers = (
        create_map_layers.validate()
        .handle_errors(task_instance_id="create_custom_map_layers")
        .partial(
            file_dict=load_local_shapefiles,
            **(params_dict.get("create_custom_map_layers") or {}),
        )
        .call()
    )

    td = (
        calculate_elliptical_time_density.validate()
        .handle_errors(task_instance_id="td")
        .partial(
            crs="ESRI:53042",
            percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
            nodata_value="nan",
            band_count=1,
            **(params_dict.get("td") or {}),
        )
        .mapvalues(argnames=["trajectory_gdf"], argvalues=split_subject_traj_groups)
    )

    td_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="td_colormap")
        .partial(
            input_column_name="percentile",
            colormap="RdYlGn",
            output_column_name="percentile_colormap",
            **(params_dict.get("td_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=td)
    )

    td_map_layer = (
        create_polygon_layer.validate()
        .handle_errors(task_instance_id="td_map_layer")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "percentile_colormap", "opacity": 0.45},
            legend={
                "label_column": "percentile",
                "color_column": "percentile_colormap",
            },
            tooltip_columns=["percentile"],
            **(params_dict.get("td_map_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=td_colormap)
    )

    combine_custom_map_layers = (
        combine_map_layers.validate()
        .handle_errors(task_instance_id="combine_custom_map_layers")
        .partial(
            static_layers=create_custom_map_layers,
            **(params_dict.get("combine_custom_map_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=td_map_layer)
    )

    zoom_view_state = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_view_state")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_view_state") or {}))
        .mapvalues(argnames=["gdf"], argvalues=td_colormap)
    )

    zip_layers_view = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_layers_view")
        .partial(
            left=combine_custom_map_layers,
            right=zoom_view_state,
            **(params_dict.get("zip_layers_view") or {}),
        )
        .call()
    )

    td_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="td_ecomap")
        .partial(
            tile_layers=base_map_defs,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Home Range Metrics"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("td_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=zip_layers_view)
    )

    td_ecomap_html_url = (
        persist_text.validate()
        .handle_errors(task_instance_id="td_ecomap_html_url")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("td_ecomap_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=td_ecomap)
    )

    td_map_widget = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="td_map_widget")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Collared Lions Home Range Ecomap",
            **(params_dict.get("td_map_widget") or {}),
        )
        .map(argnames=["view", "data"], argvalues=td_ecomap_html_url)
    )

    td_grouped_map_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="td_grouped_map_widget")
        .partial(
            widgets=td_map_widget, **(params_dict.get("td_grouped_map_widget") or {})
        )
        .call()
    )

    lg_dashboard = (
        gather_dashboard.validate()
        .handle_errors(task_instance_id="lg_dashboard")
        .partial(
            details=workflow_details,
            widgets=td_grouped_map_widget,
            time_range=time_range,
            groupers=groupers,
            **(params_dict.get("lg_dashboard") or {}),
        )
        .call()
    )

    collared_html_png = (
        html_to_png.validate()
        .handle_errors(task_instance_id="collared_html_png")
        .partial(
            output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            config={"wait_for_timeout": 50000},
            **(params_dict.get("collared_html_png") or {}),
        )
        .mapvalues(argnames=["html_path"], argvalues=td_ecomap_html_url)
    )

    collared_subject_doc_widget = (
        create_doc_figure.validate()
        .handle_errors(task_instance_id="collared_subject_doc_widget")
        .partial(
            heading="Home Range Ecomap",
            level=3,
            **(params_dict.get("collared_subject_doc_widget") or {}),
        )
        .mapvalues(argnames=["filepath"], argvalues=collared_html_png)
    )

    gather_widgets = (
        prepare_widget_list.validate()
        .handle_errors(task_instance_id="gather_widgets")
        .partial(**(params_dict.get("gather_widgets") or {}))
        .mapvalues(argnames=["widgets"], argvalues=collared_subject_doc_widget)
    )

    create_report = (
        gather_doc.validate()
        .handle_errors(task_instance_id="create_report")
        .partial(
            title="Report",
            time_range=time_range,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename="collared_report",
            doc_widgets=gather_widgets,
            **(params_dict.get("create_report") or {}),
        )
        .call()
    )

    return create_report
