# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Literal, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat


class WorkflowDetails(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str = Field(..., title="Workflow Name")
    description: Optional[str] = Field("", title="Workflow Description")


class SubjectObs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject_group_name: str = Field(
        ...,
        description="⚠️ The use of a group with mixed subtypes could lead to unexpected results",
        title="Subject Group Name",
    )


class ZoomToEnvelope(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expansion_factor: Optional[float] = Field(
        1.05,
        description="Factor to expand the bounding box (e.g., 1.2 = 20% larger)",
        title="Expansion Factor",
    )


class TimezoneInfo(BaseModel):
    label: str = Field(..., title="Label")
    tzCode: str = Field(..., title="Tzcode")
    name: str = Field(..., title="Name")
    utc: str = Field(..., title="Utc")


class SpatialGrouper(BaseModel):
    spatial_index_name: str = Field(..., title="Spatial Regions")


class TemporalGrouper(BaseModel):
    temporal_index: str = Field(..., title="Time")


class ValueGrouper(BaseModel):
    index_name: str = Field(..., title="Category")


class EarthRangerConnection(BaseModel):
    name: str = Field(..., title="Data Source")


class TrajectorySegmentFilter(BaseModel):
    min_length_meters: Optional[confloat(ge=0.001)] = Field(
        0.001, title="Minimum Segment Length (Meters)"
    )
    max_length_meters: Optional[confloat(gt=0.001)] = Field(
        100000, title="Maximum Segment Length (Meters)"
    )
    min_time_secs: Optional[confloat(ge=1.0)] = Field(
        1, title="Minimum Segment Duration (Seconds)"
    )
    max_time_secs: Optional[confloat(gt=1.0)] = Field(
        172800, title="Maximum Segment Duration (Seconds)"
    )
    min_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        0.01, title="Minimum Segment Speed (Kilometers per Hour)"
    )
    max_speed_kmhr: Optional[confloat(gt=0.001)] = Field(
        500, title="Maximum Segment Speed (Kilometers per Hour)"
    )


class AutoScaleOrCustom(str, Enum):
    Auto_scale = "Auto-scale"


class AutoScaleGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Auto-scale"] = Field(
        "Auto-scale", title="Grid Cell Size"
    )


class AutoScaleOrCustom1(str, Enum):
    Customize = "Customize"


class CustomGridCellSize(BaseModel):
    auto_scale_or_custom: Literal["Customize"] = Field(
        "Customize", title="Grid Cell Size"
    )
    grid_cell_size: Optional[confloat(lt=10000.0, gt=0.0)] = Field(
        5000,
        description="Define the resolution of the raster grid (in the unit of measurement defined by the coordinate reference system set below). A smaller grid cell size provides more detail, while a larger size generalizes the data.",
        title="Custom Grid Cell Size",
    )


class TimeRange(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    since: datetime = Field(..., description="The start time", title="Since")
    until: datetime = Field(..., description="The end time", title="Until")
    timezone: Optional[TimezoneInfo] = Field(None, title="Timezone")
    time_format: Optional[str] = Field(
        "%d %b %Y %H:%M:%S", description="The time format", title="Time Format"
    )


class Groupers(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    groupers: Optional[List[Union[ValueGrouper, TemporalGrouper, SpatialGrouper]]] = (
        Field(
            None,
            description="            Specify how the data should be grouped to create the views for your dashboard.\n            This field is optional; if left blank, all the data will appear in a single view.\n            ",
            title=" ",
        )
    )


class ErClientName(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    data_source: EarthRangerConnection = Field(
        ..., description="Select one of your configured data sources.", title=""
    )


class SubjectTraj(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    trajectory_segment_filter: Optional[TrajectorySegmentFilter] = Field(
        default_factory=lambda: TrajectorySegmentFilter.model_validate(
            {
                "min_length_meters": 0.001,
                "max_length_meters": 100000,
                "min_time_secs": 1,
                "max_time_secs": 172800,
                "min_speed_kmhr": 0.01,
                "max_speed_kmhr": 500,
            }
        ),
        description="Filter track data by setting limits on track segment length, duration, and speed. Segments outside these bounds are removed, reducing noise and to focus on meaningful movement patterns.",
        title=" ",
    )


class Td(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    auto_scale_or_custom_cell_size: Optional[
        Union[AutoScaleGridCellSize, CustomGridCellSize]
    ] = Field(
        default_factory=lambda: AutoScaleGridCellSize.model_validate(
            {"auto_scale_or_custom": "Auto-scale"}
        ),
        title="Grid Cell Size",
    )
    max_speed_factor: Optional[float] = Field(
        1.05,
        description="An estimate of the subject's maximum speed as a factor of the maximum measured speed value in the dataset.",
        title="Max Speed Factor (Kilometers per Hour)",
    )
    expansion_factor: Optional[float] = Field(
        1.05,
        description="Controls how far time density values spread across the grid, affecting the smoothness of the output.",
        title="Shape Buffer Expansion Factor",
    )


class TimeDensityMap(BaseModel):
    td: Optional[Td] = Field(None, title="")
    zoom_to_envelope: Optional[ZoomToEnvelope] = Field(None, title="zoom to envelope")


class FormData(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    workflow_details: Optional[WorkflowDetails] = Field(
        None,
        description="Add information that will help to differentiate this workflow from another.",
        title="Set Workflow Details",
    )
    time_range: Optional[TimeRange] = Field(
        None,
        description="Choose the period of time to analyze.",
        title="Define time range",
    )
    groupers: Optional[Groupers] = Field(None, title="Set Groupers")
    er_client_name: Optional[ErClientName] = Field(None, title="Data Source")
    subject_obs: Optional[SubjectObs] = Field(
        None, title="Get Subject Group observations from EarthRanger"
    )
    subject_traj: Optional[SubjectTraj] = Field(
        None, title="Transform relocations to trajectories"
    )
    Time_density_map: Optional[TimeDensityMap] = Field(
        None,
        alias="Time density map",
        description="These settings show a grid-based heatmap showing where subjects spent the most time.",
    )
