# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪


from ecoscope_workflows_core.graph import DependsOn, Graph, Node

from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps
from ecoscope_workflows_ext_lion_guardians.tasks import load_map_files
from ecoscope_workflows_ext_lion_guardians.tasks import create_map_layers

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import process_relocations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory,
)
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_classification
from ecoscope_workflows_core.tasks.groupby import split_groups
from ecoscope_workflows_core.tasks.transformation import sort_values
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_core.tasks.transformation import map_values_with_unit
from ecoscope_workflows_core.tasks.transformation import map_columns
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polyline_layer
from ecoscope_workflows_core.tasks.skip import any_is_empty_df
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped
from ecoscope_workflows_ext_ecoscope.tasks.analysis import summarize_df
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_ext_lion_guardians.tasks import combine_map_layers
from ecoscope_workflows_ext_lion_guardians.tasks import create_view_state_from_gdf
from ecoscope_workflows_ext_lion_guardians.tasks import zip_grouped_by_key
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import create_map_widget_single_view
from ecoscope_workflows_core.tasks.skip import never
from ecoscope_workflows_core.tasks.results import merge_widget_views
from ecoscope_workflows_core.tasks.results import gather_dashboard

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "groupers": [],
        "er_client_name": [],
        "base_map_defs": [],
        "load_local_shapefiles": [],
        "create_custom_map_layers": ["load_local_shapefiles"],
        "subject_group_observations": ["er_client_name", "time_range"],
        "subject_relocations": ["subject_group_observations"],
        "subject_trajectory": ["subject_relocations"],
        "traj_add_temporal_index": ["subject_trajectory", "groupers"],
        "classify_trajectory_speed": ["traj_add_temporal_index"],
        "split_subject_traj_groups": ["classify_trajectory_speed", "groupers"],
        "sort_trajectories_speed": ["split_subject_traj_groups"],
        "colormap_traj_speed": ["sort_trajectories_speed"],
        "speed_bin_legend_with_unit": ["colormap_traj_speed"],
        "speed_val_with_unit": ["speed_bin_legend_with_unit"],
        "rename_speed_display_columns": ["speed_val_with_unit"],
        "traj_map_layers": ["rename_speed_display_columns"],
        "summary_trajectory_table": ["split_subject_traj_groups"],
        "save_summary_table": ["summary_trajectory_table"],
        "combine_custom_map_layers": ["create_custom_map_layers", "traj_map_layers"],
        "zoom_view_state": ["rename_speed_display_columns"],
        "zip_layers_view": ["combine_custom_map_layers", "zoom_view_state"],
        "draw_combined_ecomap": ["base_map_defs", "zip_layers_view"],
        "ecomap_url": ["draw_combined_ecomap"],
        "speed_map_widget": ["ecomap_url"],
        "td_grouped_map_widget": ["speed_map_widget"],
        "lg_dashboard": [
            "workflow_details",
            "td_grouped_map_widget",
            "time_range",
            "groupers",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .handle_errors(task_instance_id="workflow_details")
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .handle_errors(task_instance_id="time_range")
            .set_executor("lithops"),
            partial={
                "time_format": "%d %b %Y %H:%M:%S %Z",
            }
            | (params_dict.get("time_range") or {}),
            method="call",
        ),
        "groupers": Node(
            async_task=set_groupers.validate()
            .handle_errors(task_instance_id="groupers")
            .set_executor("lithops"),
            partial=(params_dict.get("groupers") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .handle_errors(task_instance_id="er_client_name")
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "base_map_defs": Node(
            async_task=set_base_maps.validate()
            .handle_errors(task_instance_id="base_map_defs")
            .set_executor("lithops"),
            partial=(params_dict.get("base_map_defs") or {}),
            method="call",
        ),
        "load_local_shapefiles": Node(
            async_task=load_map_files.validate()
            .handle_errors(task_instance_id="load_local_shapefiles")
            .set_executor("lithops"),
            partial=(params_dict.get("load_local_shapefiles") or {}),
            method="call",
        ),
        "create_custom_map_layers": Node(
            async_task=create_map_layers.validate()
            .handle_errors(task_instance_id="create_custom_map_layers")
            .set_executor("lithops"),
            partial={
                "file_dict": DependsOn("load_local_shapefiles"),
            }
            | (params_dict.get("create_custom_map_layers") or {}),
            method="call",
        ),
        "subject_group_observations": Node(
            async_task=get_subjectgroup_observations.validate()
            .handle_errors(task_instance_id="subject_group_observations")
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "raise_on_empty": False,
                "include_details": False,
                "include_subjectsource_details": False,
            }
            | (params_dict.get("subject_group_observations") or {}),
            method="call",
        ),
        "subject_relocations": Node(
            async_task=process_relocations.validate()
            .handle_errors(task_instance_id="subject_relocations")
            .set_executor("lithops"),
            partial={
                "observations": DependsOn("subject_group_observations"),
                "relocs_columns": [
                    "groupby_col",
                    "fixtime",
                    "junk_status",
                    "geometry",
                    "extra__subject__name",
                    "extra__subject__subject_subtype",
                    "extra__subject__sex",
                ],
                "filter_point_coords": [
                    {"x": 180.0, "y": 90.0},
                    {"x": 0.0, "y": 0.0},
                    {"x": 1.0, "y": 1.0},
                ],
            }
            | (params_dict.get("subject_relocations") or {}),
            method="call",
        ),
        "subject_trajectory": Node(
            async_task=relocations_to_trajectory.validate()
            .handle_errors(task_instance_id="subject_trajectory")
            .set_executor("lithops"),
            partial={
                "relocations": DependsOn("subject_relocations"),
            }
            | (params_dict.get("subject_trajectory") or {}),
            method="call",
        ),
        "traj_add_temporal_index": Node(
            async_task=add_temporal_index.validate()
            .handle_errors(task_instance_id="traj_add_temporal_index")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("subject_trajectory"),
                "time_col": "segment_start",
                "groupers": DependsOn("groupers"),
                "cast_to_datetime": True,
                "format": "mixed",
            }
            | (params_dict.get("traj_add_temporal_index") or {}),
            method="call",
        ),
        "classify_trajectory_speed": Node(
            async_task=apply_classification.validate()
            .handle_errors(task_instance_id="classify_trajectory_speed")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("traj_add_temporal_index"),
                "input_column_name": "speed_kmhr",
                "output_column_name": "speed_bins",
                "classification_options": {"scheme": "equal_interval", "k": 6},
                "label_options": {"label_ranges": False, "label_decimals": 1},
            }
            | (params_dict.get("classify_trajectory_speed") or {}),
            method="call",
        ),
        "split_subject_traj_groups": Node(
            async_task=split_groups.validate()
            .handle_errors(task_instance_id="split_subject_traj_groups")
            .set_executor("lithops"),
            partial={
                "df": DependsOn("classify_trajectory_speed"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("split_subject_traj_groups") or {}),
            method="call",
        ),
        "sort_trajectories_speed": Node(
            async_task=sort_values.validate()
            .handle_errors(task_instance_id="sort_trajectories_speed")
            .set_executor("lithops"),
            partial={
                "column_name": "speed_bins",
                "ascending": True,
                "na_position": "last",
            }
            | (params_dict.get("sort_trajectories_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "colormap_traj_speed": Node(
            async_task=apply_color_map.validate()
            .handle_errors(task_instance_id="colormap_traj_speed")
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_bins",
                "output_column_name": "speed_bins_colormap",
                "colormap": [
                    "#1a9850",
                    "#91cf60",
                    "#d9ef8b",
                    "#fee08b",
                    "#fc8d59",
                    "#d73027",
                ],
            }
            | (params_dict.get("colormap_traj_speed") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("sort_trajectories_speed"),
            },
        ),
        "speed_bin_legend_with_unit": Node(
            async_task=map_values_with_unit.validate()
            .handle_errors(task_instance_id="speed_bin_legend_with_unit")
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_bins",
                "output_column_name": "speed_bins_formatted",
                "original_unit": "km/h",
                "new_unit": "km/h",
                "decimal_places": 1,
            }
            | (params_dict.get("speed_bin_legend_with_unit") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("colormap_traj_speed"),
            },
        ),
        "speed_val_with_unit": Node(
            async_task=map_values_with_unit.validate()
            .handle_errors(task_instance_id="speed_val_with_unit")
            .set_executor("lithops"),
            partial={
                "input_column_name": "speed_kmhr",
                "output_column_name": "speed_kmhr",
                "original_unit": "km/h",
                "new_unit": "km/h",
                "decimal_places": 1,
            }
            | (params_dict.get("speed_val_with_unit") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("speed_bin_legend_with_unit"),
            },
        ),
        "rename_speed_display_columns": Node(
            async_task=map_columns.validate()
            .handle_errors(task_instance_id="rename_speed_display_columns")
            .set_executor("lithops"),
            partial={
                "drop_columns": [],
                "retain_columns": [],
                "rename_columns": {
                    "segment_start": "Start",
                    "timespan_seconds": "Duration (s)",
                    "speed_kmhr": "Speed (kph)",
                    "extra__name": "Subject Name",
                    "extra__sex": "Subject Sex",
                },
            }
            | (params_dict.get("rename_speed_display_columns") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("speed_val_with_unit"),
            },
        ),
        "traj_map_layers": Node(
            async_task=create_polyline_layer.validate()
            .handle_errors(task_instance_id="traj_map_layers")
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "layer_style": {"color_column": "speed_bins_colormap"},
                "legend": {
                    "label_column": "speed_bins_formatted",
                    "color_column": "speed_bins_colormap",
                },
                "tooltip_columns": [
                    "Start",
                    "Duration (s)",
                    "Speed (kph)",
                    "Nighttime",
                    "Subject Name",
                    "Subject Sex",
                ],
            }
            | (params_dict.get("traj_map_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geodataframe"],
                "argvalues": DependsOn("rename_speed_display_columns"),
            },
        ),
        "summary_trajectory_table": Node(
            async_task=summarize_df.validate()
            .handle_errors(task_instance_id="summary_trajectory_table")
            .set_executor("lithops"),
            partial={
                "groupby_cols": ["extra__name"],
                "summary_params": [
                    {
                        "display_name": "Total Distance",
                        "aggregator": "sum",
                        "column": "dist_meters",
                        "original_unit": "m",
                        "new_unit": "km",
                        "decimal_places": 2,
                    }
                ],
            }
            | (params_dict.get("summary_trajectory_table") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("split_subject_traj_groups"),
            },
        ),
        "save_summary_table": Node(
            async_task=persist_df.validate()
            .handle_errors(task_instance_id="save_summary_table")
            .set_executor("lithops"),
            partial={
                "filetype": "csv",
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("save_summary_table") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["df"],
                "argvalues": DependsOn("summary_trajectory_table"),
            },
        ),
        "combine_custom_map_layers": Node(
            async_task=combine_map_layers.validate()
            .handle_errors(task_instance_id="combine_custom_map_layers")
            .set_executor("lithops"),
            partial={
                "static_layers": DependsOn("create_custom_map_layers"),
            }
            | (params_dict.get("combine_custom_map_layers") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["grouped_layers"],
                "argvalues": DependsOn("traj_map_layers"),
            },
        ),
        "zoom_view_state": Node(
            async_task=create_view_state_from_gdf.validate()
            .handle_errors(task_instance_id="zoom_view_state")
            .set_executor("lithops"),
            partial={
                "pitch": 0,
                "bearing": 0,
            }
            | (params_dict.get("zoom_view_state") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["gdf"],
                "argvalues": DependsOn("rename_speed_display_columns"),
            },
        ),
        "zip_layers_view": Node(
            async_task=zip_grouped_by_key.validate()
            .handle_errors(task_instance_id="zip_layers_view")
            .set_executor("lithops"),
            partial={
                "left": DependsOn("combine_custom_map_layers"),
                "right": DependsOn("zoom_view_state"),
            }
            | (params_dict.get("zip_layers_view") or {}),
            method="call",
        ),
        "draw_combined_ecomap": Node(
            async_task=draw_ecomap.validate()
            .handle_errors(task_instance_id="draw_combined_ecomap")
            .set_executor("lithops"),
            partial={
                "tile_layers": DependsOn("base_map_defs"),
                "north_arrow_style": {"placement": "top-left"},
                "legend_style": {"placement": "bottom-right", "title": "Speeds(Km/h)"},
                "static": False,
                "title": None,
                "max_zoom": 20,
            }
            | (params_dict.get("draw_combined_ecomap") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["geo_layers", "view_state"],
                "argvalues": DependsOn("zip_layers_view"),
            },
        ),
        "ecomap_url": Node(
            async_task=persist_text.validate()
            .handle_errors(task_instance_id="ecomap_url")
            .set_executor("lithops"),
            partial={
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("ecomap_url") or {}),
            method="mapvalues",
            kwargs={
                "argnames": ["text"],
                "argvalues": DependsOn("draw_combined_ecomap"),
            },
        ),
        "speed_map_widget": Node(
            async_task=create_map_widget_single_view.validate()
            .handle_errors(task_instance_id="speed_map_widget")
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Speed Map",
            }
            | (params_dict.get("speed_map_widget") or {}),
            method="map",
            kwargs={
                "argnames": ["view", "data"],
                "argvalues": DependsOn("ecomap_url"),
            },
        ),
        "td_grouped_map_widget": Node(
            async_task=merge_widget_views.validate()
            .handle_errors(task_instance_id="td_grouped_map_widget")
            .set_executor("lithops"),
            partial={
                "widgets": DependsOn("speed_map_widget"),
            }
            | (params_dict.get("td_grouped_map_widget") or {}),
            method="call",
        ),
        "lg_dashboard": Node(
            async_task=gather_dashboard.validate()
            .handle_errors(task_instance_id="lg_dashboard")
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": DependsOn("td_grouped_map_widget"),
                "time_range": DependsOn("time_range"),
                "groupers": DependsOn("groupers"),
            }
            | (params_dict.get("lg_dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
