workflow_details:
  description: ''
  name: Collared Lions Report
groupers:
  groupers:
    - subject_sex
er_client_name:
  data_source:
    name: lg
base_map_defs:
  base_maps:
    - url: >-
        https://server.arcgisonline.com/ArcGIS/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}
      opacity: 1
      max_zoom: 20
subject_traj:
  trajectory_segment_filter:
    min_length_meters: 0.001
    max_length_meters: 100000
    min_time_secs: 1
    max_time_secs: 21600
    min_speed_kmhr: 0.01
    max_speed_kmhr: 15
td:
  auto_scale_or_custom_cell_size:
    auto_scale_or_custom: Auto-scale
  max_speed_factor: 1.05
  expansion_factor: 1.05
time_range:
  since: '2025-01-01T07:07:00.000Z'
  until: '2025-06-01T07:07:00.000Z'
subject_obs:
  subject_group_name: Collared Lions
